# Site
url: https://danielle-li.github.io
name: Danielle Li

# Custom settings (GitHub Pages Starter)
custom:
  # required
  is_development: false

  description: Associate Professor, MIT Sloan. Faculty Research Fellow, NBER.

# Handling / Reading
destination: ./../public
safe: true
ignore_theme_config: true
strict_front_matter: true
include:
  - _pages
  - _papers

collections:
  - papers

keep_files:
  - assets # generate by gulp, not jekyll

exclude:
  - _data/rev-manifest.json
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock

# Conversion
markdown: kramdown
incremental: false

# Output
permalink: pretty
timezone: America/New_York

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false
