# Site Variables
url: https://danielle-li.github.io

# Custom settings (GitHub Pages starter)
custom_settings:
  # required
  is_development: false

  # optional/convenience
  name: Danielle Li
  description: Associate Professor, MIT Sloan. Faculty Research Fellow, NBER.

# Handling / Reading
safe: true
include:
  - _pages

keep_files:
  - assets # generate by gulp

exclude:
  - _data/rev-manifest.json
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock

# Conversion
markdown: kramdown

# Output
permalink: pretty
timezone: America/New_York

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false
